### ISSUE TITLE
Lemmas for feminine and masculine adjectives

### ISSUE THREAD

**Issue by tomsbergmanis** [UniversalDependencies/UD_Latvian-LVTB#3]
Dear colleagues, 
In the Latvian UDT, the feminine and masculine forms of the same adjective have separate lemmas. This makes the feminine and masculine forms of adjectives seemingly two unrelated words as they are not related to each other via the same lemma.
As long as there might be a subtle linguistic motivation for such conceptualization, in my opinion, this only creates data sparsity and causes inconsistencies with other data sets. 

Let me know if I can be of any help if you decide to implement the changes. 
T. Bergmanis
Ph.D. candidate at University of Edinburgh

**Comment by lauma** [comment]
I'll ask around. There was some linguistic reasoning behind it a long time ago, but I'm not sure if it is relevant anymore.

**Comment by tomsbergmanis** [comment]
Thanks! 
I am asking because it would be nice to reach a consistency between Latvian UDT and UniMorph morphological standards. This seemed like an artifact that could be changed in UDT (while most of the work in my opinion lays on the UniMorph side).

**Comment by lauma** [comment]
Yes, for UDv2.3 adjectives and numerals will have the same lemma for both genders, with an exception for adjectival surnames like _Anna Baltā_ where lemma at least for now will stay capitalized `Baltā`. I don't know, if it is the best solution regarding to surnames, but we need to do more thinking on that. Also, those cases are fairly rare: if remember correctly, I saw 3 such surnames on the whole corpus, two were some contemporary persons and one was _Ivans Bargais_ (Ivan the Terrible).

**Comment by lauma** [comment]
We also speculated that there might be some adjectives that are used only in feminine gender and, thus, shuldn't have masculine lemma (Tezaurs.lv reports _ālava_ as such), but it looks like currently there are no such cases in treebank.

**Comment by tomsbergmanis** [comment]
Cool, cool, cool! 
Thank you very much! 
Toms
