### ISSUE TITLE
Features for participles

### ISSUE THREAD

**Issue by Nofenigma** [UniversalDependencies/UD_Latvian-LVTB#4]
I wonder why Latvian has aspect features for some verb forms (I'm not even sure that the annotation is consistent), if there is no clear evidence in favour of the analysis of aspect in Latvian as a true grammatical feature (even in Lithuanian, where imperfective verbal derivatives exist, the situation is far from the Slavic-style opposition).
In addition, I have noticed that voice is marked for finite verb forms, but not for participles, while the opposite situation would make much more sense (it's true participles that express the active/passive contrast in Latvian). This is especially strange, considering that your morphological analyzer does have this feature.

**Comment by lauma** [comment]
If nothing has gone wrong in conversion script, declensible participles (-is, -ies, -ts, -ošs, -ams, -āms) have voice, while partially declensible participles (-dams, -damies) and non-declensible participles (-ot, -oties, -am, -ām) don't - basically the same as the moprhological analyzer does and the theory books says. If this is not the case, I'll go investigate what's worng with conversion script. The traditional definition is that -is, -ies, -ts are passive participles and -ošs, -ams, -āms are active participles.

About finite forms... Well, the current solution stems from traditional syntax again, even though the result in token-by-token morphotagging looks a bit weird. Traditional syntax says that Latvian has both active and passive voice, its just all passive voice constructions are analytical and are constructed from 2 or more tokens - an auxiliary verb in active voice and pasive participle, e.g., _[tas] tika darīts_. Thus, when voice is assigned in a scope of token, all finite forms get active voice tag, and the passive participle is the component making analytical form to be pasive. Of course, we can remove a voice feature from finite forms, if that is more apropriate for UD guidelines, but it was added as it seemed to give more informative data this way.

About aspect: yes, mostly such information is lexical in Latvian. Currently it is tagged for three kinds of declensible participles - imperfect for -ošs participles (_koks ir ziedošs_ 'tree is blooming') and perfect for -ts, -is, -ies (_tas ir pabeigts_ 'it is finished') participles, as (1) these participles are morphologically distinguishable from other verb forms and (2) and by their nature they carry information if the action is ongoing or bounded somewhere in the past, so it is the closest to aspect thing one can get anywhere in Latvian.

**Comment by lauma** [comment]
About that "if nothing has gone wrong in conversion script" part.

Latvian UD treebank is converted, not natively annotated, but it contains original morpholgical tags in the XPOS column (original [specification](http://sintakse.korpuss.lv/docs/v2-3/SemTi-Kamols_morphotags.xlsx)). So if there are systemic descreepancies, e.g., originaly pasive participles are UD-tagged as active or something, please let me know, I'll tweak the convenversion script for next release.

**Comment by Nofenigma** [comment]
Thanks a lot for the comments. I do suspect that something went wrong with conversion (hope that @dan-zeman can help to check that), as I looked for different examples, and I don't see any voice features for participles in many places, though they are present in the original MULTEXT features (xpos).

More particularly, I have just tried to check the training data of your treebank (from this repository, https://raw.githubusercontent.com/UniversalDependencies/UD_Latvian-LVTB/master/lv_lvtb-ud-train.conllu), and many participles in -oš(s) have Voice=Pass, while almost all passive participles have no voice feature at all. So I'm very sorry, but it seems that this should be improved before the next release, if we consider that something else but UPOS can also be important.

**Comment by lauma** [comment]
Thanks! I'll sort it out.

**Comment by lauma** [comment]
Okay, I hope that as of https://github.com/UniversalDependencies/UD_Latvian-LVTB/commit/8bff2dc5af73689b8a3e611aee4af7d345314afd (it is currently on the dev branch) Voice mistagging is sorted out. If you find something else, let me know.

**Comment by dan-zeman** [comment]
> Of course, we can remove a voice feature from finite forms, if that is more apropriate for UD guidelines

I think it is quite OK to have the feature there. Precisely as you say: the token is in the active form, even though it participates in a periphrastic form that, as a whole, is passive.
