### ISSUE TITLE
Test sentence a-p3759-p9s2

### ISSUE THREAD

**Issue by tomsbergmanis** [UniversalDependencies/UD_Latvian-LVTB#5]
Hi again, 
I was wondering if the node a-p3759-p9s2w2 in the test sentece a-p3759-p9s2:
`Blakus lāzeriem-mērierīcēm ir vajadzīga attēla veidošanas programmatūra, kas saliks milzu skaitu lāzera stara "atspulgus" objekta datorattēlā.`
is indeed analysed correctly as 
`2	lāzeriem-mērierīcēm	lāzeriem-mērierīcēm	SYM	xx	_	4	obl	4:obl:blakus	LvtbNodeId=a-p3759-p9s2w2`

It seems to be an error, doesn't it? 

Paldies, 
Toms Bergmanis 
PhD Candidate at University of Edinburgh
http://homepages.inf.ed.ac.uk/s1044253

**Comment by lrituma** [comment]
Hi,
Yes, it is an error, we will correct it to the next UD release. Thank You for the notice.
Best regards,
Laura Rituma

**Comment by lauma** [comment]
Ok, closing then.
