### ISSUE TITLE
lemmatization error at LvtbNodeId=a-z108-p193s5w1

### ISSUE THREAD

**Issue by tomsbergmanis** [UniversalDependencies/UD_Latvian-LVTB#6]
Hi again, 
LvtbNodeId=a-z108-p193s5w1
`1	Turklāt	turklā	SCONJ	cs	_	6	mark	6:mark	LvtbNodeId=a-z108-p193s5w1`
seem to have a lemmatization error. 

Toms Bergmanis 
PhD Candidate at University of Edinburgh
http://homepages.inf.ed.ac.uk/s1044253

**Comment by lrituma** [comment]
Thanks, 
we corrected lemma.
Laura Rituma

**Comment by lauma** [comment]
Ok, closing then.
