### ISSUE TITLE
Tagging error in sent_id = a-d27-p21s2

### ISSUE THREAD

**Issue by tomsbergmanis** [UniversalDependencies/UD_Latvian-LVTB#7]
Sveiki!
 sent_id = a-d27-p21s2
 text = Jaunākā iespēja ir pirms nāves konsultēties ar postmortālo psihoterapeitu, kura uzdevums ir mazināt šoku, ko apziņa pārdzīvo nāves **laikā**.
Kļūda vārda **laikā** lemmā un vārdšķirā:
21	laikā	**Laika**	**PROPN**	npfsl4	Case=Loc|Gender=Fem|Number=Sing	19	obl	19:obl:loc	LvtbNodeId=a-d27-p21s2w21|SpaceAfter=No

Toms Bergmanis 
PhD Candidate at University of Edinburgh
http://homepages.inf.ed.ac.uk/s1044253

**Comment by lrituma** [comment]
Labdien!
Paldies, kļūda izlabota, pareizā versija parādīsies nākamajā datu relīzē.
Ar sveicienu, 
Laura Rituma

**Comment by lauma** [comment]
Tad es aizvēršu. Ja pēc nākamās relīzes turpina būt, attaisīs par jaunu.
