### ISSUE TITLE
Some inconsistencies in lemmas

### ISSUE THREAD

**Issue by tomsbergmanis** [UniversalDependencies/UD_Latvian-LVTB#8]
Sveiki, 
Pamanīju arī šo:
Teikumā ar ID a-p3754-p4s3 **gada** lemmatizēts kā **Gadis**, kamēr visur citur kā **gads**. 
Teikumā ar ID a-d60-p5s5 **piemēram** lemmatizēts kā **piemēram**, kamēr visur citur kā **piemērs**. 
Teikumā ar ID a-p3348_r1-p1s2 **tam** lemmatizēts kā **tam**, kamēr visur citur kā **tas**. 
Teikumā ar ID a-d27-p25s3  **mani** lemmatizēts kā **mans**, kamēr visur citur kā **es**. 
Teikumos ar ID a-d62-p15s3 un a-d62-p15s5  **–** lemmatizēts kā **-**, kamēr visur citur kā **–**. 
Teikumā ar ID a-p1299-p4s1 **latu** lemmatizēts kā **lata**, kamēr visur citur kā **lats**.
Teikumā ar ID a-c60-p4s11 **reizi** lemmatizēts kā **reizi**, kamēr visur citur kā **reize**.

Toms Bergmanis 
PhD Candidate at University of Edinburgh
http://homepages.inf.ed.ac.uk/s1044253

**Comment by lrituma** [comment]
Paldies, dati izlaboti, pareizā versija būs nākamā relīzē.
Nelabojām:
"Teikumā ar ID a-d27-p25s3 *mani lemmatizēts kā mans, kamēr visur citur kā es." - lemma pareiza, jo vietniekvārda "mans" daudzskaitļa nominatīvs ir homoforma ar vietniekvārda "es" vienskaitļa akuzatīvu. 
Ar cieņu, 
Laura Rituma

**Comment by tomsbergmanis** [comment]
Paldies!


Toms Bergmanis

PhD Candidate at University of Edinburgh

http://homepages.inf.ed.ac.uk/s1044253
