### ISSUE TITLE
Jautājums par personvārdu marķējumu

### ISSUE THREAD

**Issue by tomsbergmanis** [UniversalDependencies/UD_Latvian-LVTB#9]
Sveiki, 
Vai ir kāda konkrēta pazīme pēc kuras varētu noteikt, ka ```PRPN``` ir personvārds? 
Ievēroju, ka personvārdiem, kas ir formā Vārds Uzvārds, uzvārda daļa marķēta ar ```flat:name```. Šis protams, nepalīdz vispārīgā gadījumā. Iedomājos, ka varbūt ir vēl kādi marķieri par ko neesmu iedomājis.

Paldies, 
Toms

**Comment by lauma** [comment]
Cik tālu es zinu, UD nedod nekādus universālus veidus, kā atpazīt personvārdus, un `flat:name` var lietot arī citiem īpašvārdiem, piemēram, vietvārdiem. Bet varbūt @PeterisP zinās pakomentēt, vai/kā var lietot https://github.com/PeterisP/morphology, lai dabūtu kādas norādes par to. Cik zinu, tur bija PMLP datubāze ielikta, kas varbūt ļautu identificēt vismaz Latvijā reģistrētos personu vārdus.

**Comment by tomsbergmanis** [comment]
Paldies!
